config-version: 2
require-dbt-version: [">=1.0.0", "<2.0.0"]

name: 'netsuite_source'
version: '0.4.2'

models:
  netsuite_source:
    +materialized: table
    +schema: stg_netsuite
    tmp:
      +materialized: view

vars:
  netsuite_source:
    data_model: netsuite2

    # Netsuite.com
    accounting_books: "{{ source('netsuite','accounting_books') }}"
    accounting_periods: "{{ source('netsuite','accounting_periods') }}"
    accounts: "{{ source('netsuite','accounts') }}"
    classes: "{{ source('netsuite','classes') }}"
    consolidated_exchange_rates: "{{ source('netsuite','consolidated_exchange_rates') }}"
    currencies: "{{ source('netsuite','currencies') }}"
    customers: "{{ source('netsuite','customers') }}"
    departments: "{{ source('netsuite','departments') }}"
    expense_accounts: "{{ source('netsuite','expense_accounts') }}"
    income_accounts: "{{ source('netsuite','income_accounts') }}"
    items: "{{ source('netsuite','items') }}"
    locations: "{{ source('netsuite','locations') }}"
    subsidiaries: "{{ source('netsuite','subsidiaries') }}"
    transaction_lines: "{{ source('netsuite','transaction_lines') }}"
    transactions: "{{ source('netsuite','transactions') }}"
    vendor_types: "{{ source('netsuite','vendor_types') }}"
    vendors: "{{ source('netsuite','vendors') }}"

    # Netsuite2.com
    accounting_books_netsuite2: "{{ source('netsuite2','accountingbook') }}"
    accounting_periods_netsuite2: "{{ source('netsuite2','accountingperiod') }}"
    accounts_netsuite2: "{{ source('netsuite2','account') }}"
    classes_netsuite2: "{{ source('netsuite2','classification') }}"
    consolidated_exchange_rates_netsuite2: "{{ source('netsuite2','consolidatedexchangerate') }}"
    currencies_netsuite2: "{{ source('netsuite2','currency') }}"
    customers_netsuite2: "{{ source('netsuite2','customer') }}"
    departments_netsuite2: "{{ source('netsuite2','department') }}"
    entity_netsuite2: "{{ source('netsuite2','entity') }}"
    items_netsuite2: "{{ source('netsuite2','item') }}"
    job_netsuite2: "{{ source('netsuite2','job') }}"
    locations_netsuite2: "{{ source('netsuite2','location') }}"
    subsidiaries_netsuite2: "{{ source('netsuite2','subsidiary') }}"
    transaction_accounting_lines_netsuite2: "{{ source('netsuite2','transactionaccountingline') }}"
    transaction_lines_netsuite2: "{{ source('netsuite2','transactionline') }}"
    transactions_netsuite2: "{{ source('netsuite2','transaction') }}"
    vendors_netsuite2: "{{ source('netsuite2','vendor') }}"
    vendor_category_netsuite2: "{{ source('netsuite2', 'vendorcategory') }}"

    # might wanna add *_netsuite2 to be in line with the above
    accountingbooksubsidiaries: "{{ source('netsuite2', 'accountingbooksubsidiaries') }}"
    accountingperiodfiscalcalendars: "{{ source('netsuite2', 'accountingperiodfiscalcalendars') }}"
    accounttype: "{{ source('netsuite2', 'accounttype') }}"
    entityaddress: "{{ source('netsuite2', 'entityaddress') }}"
    locationmainaddress: "{{ source('netsuite2', 'locationmainaddress') }}"

    accounts_pass_through_columns: []
    classes_pass_through_columns: []
    departments_pass_through_columns: []
    transactions_pass_through_columns: []
    transaction_lines_pass_through_columns: []
    customers_pass_through_columns: []
    locations_pass_through_columns: []
    subsidiaries_pass_through_columns: []
    consolidated_exchange_rates_pass_through_columns: []

clean-targets:
  - target
  - dbt_modules
  - dbt_packages
