config-version: 2
require-dbt-version: [">=1.3.0", "<2.0.0"]
name: 'netsuite_source'
version: '0.10.0'

models:
  netsuite_source:
    +materialized: view
    +schema: netsuite_source
    netsuite:
      tmp:
        +materialized: view
    netsuite2:
      tmp:
        +materialized: view

vars:
  netsuite_source:
    netsuite_accounting_books: "{{ source('netsuite','accounting_books') }}"
    netsuite_accounting_periods: "{{ source('netsuite','accounting_periods') }}"
    netsuite_accounts: "{{ source('netsuite','accounts') }}"
    netsuite_classes: "{{ source('netsuite','classes') }}"
    netsuite_consolidated_exchange_rates: "{{ source('netsuite','consolidated_exchange_rates') }}"
    netsuite_currencies: "{{ source('netsuite','currencies') }}"
    netsuite_customers: "{{ source('netsuite','customers') }}"
    netsuite_departments: "{{ source('netsuite','departments') }}"
    netsuite_expense_accounts: "{{ source('netsuite','expense_accounts') }}"
    netsuite_income_accounts: "{{ source('netsuite','income_accounts') }}"
    netsuite_items: "{{ source('netsuite','items') }}"
    netsuite_locations: "{{ source('netsuite','locations') }}"
    netsuite_subsidiaries: "{{ source('netsuite','subsidiaries') }}"
    netsuite_transaction_lines: "{{ source('netsuite','transaction_lines') }}"
    netsuite_transactions: "{{ source('netsuite','transactions') }}"
    netsuite_vendor_types: "{{ source('netsuite','vendor_types') }}"
    netsuite_vendors: "{{ source('netsuite','vendors') }}"
    netsuite2_accounting_books: "{{ source('netsuite2','accounting_book') }}"
    netsuite2_accounting_periods: "{{ source('netsuite2','accounting_period') }}"
    netsuite2_accounts: "{{ source('netsuite2','account') }}"
    netsuite2_classes: "{{ source('netsuite2','classification') }}"
    netsuite2_consolidated_exchange_rates: "{{ source('netsuite2','consolidated_exchange_rate') }}"
    netsuite2_currencies: "{{ source('netsuite2','currency') }}"
    netsuite2_customers: "{{ source('netsuite2','customer') }}"
    netsuite2_departments: "{{ source('netsuite2','department') }}"
    netsuite2_employees: "{{ source('netsuite2','employee') }}"
    netsuite2_entities: "{{ source('netsuite2','entity') }}"
    netsuite2_items: "{{ source('netsuite2','item') }}"
    netsuite2_jobs: "{{ source('netsuite2','job') }}"
    netsuite2_locations: "{{ source('netsuite2','location') }}"
    netsuite2_subsidiaries: "{{ source('netsuite2','subsidiary') }}"
    netsuite2_transaction_accounting_lines: "{{ source('netsuite2','transaction_accounting_line') }}"
    netsuite2_transaction_lines: "{{ source('netsuite2','transaction_line') }}"
    netsuite2_transactions: "{{ source('netsuite2','transaction') }}"
    netsuite2_vendors: "{{ source('netsuite2','vendor') }}"
    netsuite2_vendor_categories: "{{ source('netsuite2', 'vendor_category') }}"
    netsuite2_accounting_book_subsidiaries: "{{ source('netsuite2', 'accounting_book_subsidiaries') }}"
    netsuite2_accounting_period_fiscal_calendars: "{{ source('netsuite2', 'accounting_period_fiscal_calendars') }}"
    netsuite2_account_types: "{{ source('netsuite2', 'account_type') }}"
    netsuite2_entity_address: "{{ source('netsuite2', 'entity_address') }}"
    netsuite2_location_main_address: "{{ source('netsuite2', 'location_main_address') }}"
    accounts_pass_through_columns:
      - name: "custrecord_cash_flow_category"
        alias: "lyra_cash_flow_category"
      - name: "custrecord_ebitda_category"
        alias: "lyra_ebitda_category"
      - name: "custrecord_transfer_pricing_method"
        alias: "lyra_transfer_pricing_method"
    classes_pass_through_columns: []
    departments_pass_through_columns:
      - name: "custrecord_sec_opex_category"
        alias: "lyra_sec_opex_category"
    transactions_pass_through_columns:
      - name: "custbody_subledger"
        alias: "lyra_subledger"
      - name: "custbody_subledger_id"
        alias: "lyra_subledger_id"
      - name: "typebaseddocumentnumber"
        alias: "type_based_document_number"
      - name: "tranid"
        alias: "tran_id"
      - name: "createdby"
        alias: "created_by_id"
      - name: "createddate"
        alias: "created_date"
      - name: "lastmodifiedby"
        alias: "last_modified_by_id"
      - name: "lastmodifieddate"
        alias: "last_modified_date"
    transaction_lines_pass_through_columns:
      - name: "amortizstartdate"
        alias: "amortization_start_date"
      - name: "amortizationenddate"
        alias: "amortization_end_date"
      - name: "custcol_inv_start_date"
        alias: "lyra_inv_start_date"
      - name: "custcol_inv_end_date"
        alias: "lyra_inv_end_date"
    customers_pass_through_columns: []
    locations_pass_through_columns: []
    subsidiaries_pass_through_columns:
      - name: "custrecord_transfer_pricing_markup"
        alias: "lyra_transfer_pricing_markup"
      - name: "custrecord_transfer_pricing_coa_method"
        alias: "lyra_transfer_pricing_coa_method"
    consolidated_exchange_rates_pass_through_columns: []
    vendors_pass_through_columns: []
    items_pass_through_columns: []

clean-targets:
- target
- dbt_modules
- dbt_packages
