config-version: 2
require-dbt-version: [">=1.0.0", "<2.0.0"]

name: 'netsuite_source'
version: '0.4.1'

models:
  netsuite_source:
    +materialized: table
    +schema: stg_netsuite
    tmp:
      +materialized: view

vars:
  netsuite_source:
    data_model: netsuite2

    # Netsuite.com
    accounting_books: "{{ source('netsuite','accounting_books') }}"
    accounting_periods: "{{ source('netsuite','accounting_periods') }}"
    accounts: "{{ source('netsuite','accounts') }}"
    classes: "{{ source('netsuite','classes') }}"
    consolidated_exchange_rates: "{{ source('netsuite','consolidated_exchange_rates') }}"
    currencies: "{{ source('netsuite','currencies') }}"
    customers: "{{ source('netsuite','customers') }}"
    departments: "{{ source('netsuite','departments') }}"
    expense_accounts: "{{ source('netsuite','expense_accounts') }}"
    income_accounts: "{{ source('netsuite','income_accounts') }}"
    items: "{{ source('netsuite','items') }}"
    locations: "{{ source('netsuite','locations') }}"
    subsidiaries: "{{ source('netsuite','subsidiaries') }}"
    transaction_lines: "{{ source('netsuite','transaction_lines') }}"
    transactions: "{{ source('netsuite','transactions') }}"
    vendor_types: "{{ source('netsuite','vendor_types') }}"
    vendors: "{{ source('netsuite','vendors') }}"

    # Netsuite2.com
    accounting_books_netsuite2: "{{ source('netsuite','accountingbook') }}"
    accounting_periods_netsuite2: "{{ source('netsuite','accountingperiod') }}"
    accounts_netsuite2: "{{ source('netsuite','account') }}"
    classes_netsuite2: "{{ source('netsuite','billingclass') }}"
    consolidated_exchange_rates_netsuite2: "{{ source('netsuite','consolidatedexchangerate') }}"
    currencies_netsuite2: "{{ source('netsuite','currency') }}"
    customers_netsuite2: "{{ source('netsuite','customer') }}"
    departments_netsuite2: "{{ source('netsuite','department') }}"
    items_netsuite2: "{{ source('netsuite','item') }}"
    locations_netsuite2: "{{ source('netsuite','location') }}"
    subsidiaries_netsuite2: "{{ source('netsuite','subsidiary') }}"
    transaction_lines_netsuite2: "{{ source('netsuite','transactionline') }}"
    transactions_netsuite2: "{{ source('netsuite','transaction') }}"
    vendors_netsuite2: "{{ source('netsuite','vendor') }}"

    accounts_pass_through_columns: []
    classes_pass_through_columns: []
    departments_pass_through_columns: []
    transactions_pass_through_columns: []
    transaction_lines_pass_through_columns: []
    customers_pass_through_columns: []
    locations_pass_through_columns: []
    subsidiaries_pass_through_columns: []
    consolidated_exchange_rates_pass_through_columns: []

clean-targets:
  - target
  - dbt_modules
  - dbt_packages
